services:
  - type: web
    name: expense-tracker
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in the Render dashboard:
    # - MONGODB_URI
    # - JWT_SECRET
